- name: Ensure nginx and ufw are installed
  ansible.builtin.apt:
    name:
      - nginx
      - ufw
    state: present

- name: Ensure nginx configuration file folder exists
  ansible.builtin.file:
    path: '{{ nginx_conf_dir }}'
    state: directory
    mode: '644'

- name: Create nginx conf
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: '{{ nginx_conf_dir }}/nginx.conf'
    mode: '644'
