- name: Run compose using project directory
  hosts: wp_servers
  gather_facts: false
  become: true
  tasks:
    - name: Ensure docker is installed
      ansible.builtin.apt:
        name:
          - docker-compose-v2
          - docker
        state: present

    - name: Ensure docker_path exists
      ansible.builtin.file:
        path: '{{ docker_path }}'
        state: directory
        mode: '755'

    - name: Copy compose file to host
      ansible.builtin.copy:
        src: templates/compose.yml.j2
        dest: '{{ docker_path }}/compose.yml'
        mode: '644'

    - name: Tear down existing containers
      community.docker.docker_compose_v2:
        project_src: '{{ docker_path }}'
        state: absent

    - name: Create new containers
      community.docker.docker_compose_v2:
        project_src: '{{ docker_path }}'
        state: present
