- name: Run compose using project directory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Tear down existing containers
      community.docker.docker_compose_v2:
        state: absent
    
    - name: Create new containers
      community.docker.docker_compose_v2:
        state: present