- name: Copy backup script
  ansible.builtin.copy:
    #TODO: doublecheck relative paths
    src: files/backup.sh
    dest: "/usr/local/bin/backup.sh"
    #FIXME: could be different?
    mode: '770'

- name: Create cron job
  # 0 */8 * * * 
  ansible.builtin.cron:
    name: backup
    minute: "0"
    hour: "*/8"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/bin/backup.sh"