- name: Copy backup script
  ansible.builtin.template:
    src: templates/backup.sh.j2
    dest: "/usr/local/bin/backup.sh"
    mode: '770'

- name: Create a cron job
  # 0 */8 * * *
  ansible.builtin.cron:
    name: backup
    minute: "0"
    hour: "*/8"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/bin/backup.sh"
