- name: Copy backup script
  ansible.builtin.template:
    #TODO: doublecheck relative paths
    src: templates/backup.sh.j2
    dest: "/usr/local/bin/backup.sh"
    #FIXME: could be different?
    mode: '777'

- name: Create a cron job
  # 0 */8 * * * 
  ansible.builtin.cron:
    name: backup
    minute: "0"
    hour: "*/8"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/local/bin/backup.sh"