- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: By default deny everything in
  community.general.ufw:
    default: deny
    direction: incoming

- name: By default allow everything out
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow http in
  community.general.ufw:
    rule: allow
    direction: in
    port: 80
    proto: tcp

- name: Allow ssh in
  community.general.ufw:
    rule: allow
    direction: in
    port: ssh
    proto: tcp

- name: Enable ufw
  community.general.ufw:
    state: enabled
